### PR TITLE
SystemUI: Remove QS navbar scrim

### PR DESCRIPTION
**Pull request by sashascurtu**
In the age of flat material design, this scrim looks outdated and
out-of-place. It's also quite ugly in the QS edit screen, where it
overlaps the edit view for no apparent reason because the edit view is
already fully opaque.

The existing notification shade scrim provides enough contrast with the
contents of the app behind the QS, and background blurring helps even
more with that, so let's just remove this scrim altogether.

Change-Id: Iaba142751aa033b30a44e23888db7e7664f0ef9f

### CODE REVIEW

**Comment by gotenksIN** [comment]
I don't like the look of this on notched devices, won't be merged until either a. It can be toggled on runtime or b. configurable by overlay

**Comment by gotenksIN** [comment]
nvm I misjudged what it is, +2 from me

**Review by gotenksIN — APPROVED** [review]

**Comment by idoybh** [comment]
Nope. We don't wanna remove that. We let apps decide on this one. Especially when there are devices which have no blur enabled. Navbar will just be invisible on white bg. Stop with the transparency madness please.

**Comment by idoybh** [comment]
btw it's about the same reason we don't merge the powermenu transparency memes. Ik it looks good, but functionality > looks.

**Comment by gotenksIN** [comment]
yeah that's not theme aware which is kinda a bummer

**Pull request closed without merging**
