### PR TITLE
fwb: metric shit ton of changes/improvments

### PR DESCRIPTION
**Pull request by gotenksIN**
tested these throughout the day, all seems fine and dandy

### CODE REVIEW

**Review by poad42 — APPROVED** [review]

**Comment by poad42** [comment]
Will wait on ido

**Comment by gotenksIN** [comment]
understandable, hence the PR name lmao

**Comment by idoybh** [comment]
@gotenksIN Please rebase this PR on top of current `eleven` branch. Thanks

**Comment by gotenksIN** [comment]
alright

**Comment by idoybh** [comment]
That's too much for me to read the whole of it @poad42 @gotenksIN . I just feel like trusting @gotenksIN and merging this. Where are these commits from btw?

**Comment by gotenksIN** [comment]
kdrag0n's proton aosp / aosip gerrit / derp

**Review by idoybh — APPROVED** [review]

**Pull request merged**
