### PR TITLE
FODCircleView: hide fod while alphanumeric password is being asked

### PR DESCRIPTION
**Pull request by skpawar1305**

### CODE REVIEW

**Comment by skpawar1305** [comment]
it also fixed hide fod on aod toggle completely

**Comment by idoybh** [comment]
> it also fixed hide fod on aod toggle completely

Nothing was wrong with it. This hide call was removed on purpose

**Comment by skpawar1305** [comment]
set alphanumeric password, and when keyboard pops up at lockscreen, fod icon overlaps it

**Comment by idoybh** [comment]
> set alphanumeric password, and when keyboard pops up at lockscreen, fod icon overlaps it

I meant nothing is wrong with hide on aod.

**Comment by idoybh** [comment]
Also why did you close this PR if nothing is wrong with it?

**Comment by skpawar1305** [comment]
okay, then I guess it was related to icon dimming

when enabled, n hide fod icon on aod enabled, on aod initially the icon will be visible, unless tapped once

but mostly no one is using dimming now, so I think can be ignored

**Comment by idoybh** [comment]
> okay, then I guess it was related to icon dimming
> 
> when enabled, n hide fod icon on aod enabled, on aod initially the icon will be visible, unless tapped once
> 
> but mostly no one is using dimming now, so I think can be ignored

Weird. When we used dimming up till not so long ago it didn't happen.

**Comment by skpawar1305** [comment]
> Also why did you close this PR if nothing is wrong with it?

because, I felt sad about rejection 😅

**Comment by idoybh** [comment]
And yea. I see why this hide call is needed now. (Unrelated to AOD however). I will test and merge.

**Comment by idoybh** [comment]
> > Also why did you close this PR if nothing is wrong with it?
> 
> because, I felt sad about rejection sweat_smile

Don't worry, we don't bite. I was just a bit busy is all

**Comment by skpawar1305** [comment]
maybe you can remove all pinorpattern stuff, n just add condition for alphanumeric, I can't say for sure unless I test, just check once

**Comment by idoybh** [comment]
> maybe you can remove all pinorpattern stuff, n just add condition for alphanumeric, I can't say for sure unless I test, just check once

That depends on that class (LockPatternUtils), not on me.

**Comment by skpawar1305** [comment]
it's there in it

**Comment by idoybh** [comment]
> it's there in it

Yea just saw. Thanks. Will hide specifically for it than

**Comment by idoybh** [comment]
> it's there in it

Nope. It should just be as you wrote it actually. I think it's best... Will merge in a few

**Comment by idoybh** [comment]
thank you :) Please don't be afraid of me next time. I listen to reason. This hide call should def be there, my bad.

**Pull request merged**
